# Goal
int32[] box_ids
geometry_msgs/PoseStamped search_pose # pose where the boxes are expected so that the robot can search for them
geometry_msgs/PoseStamped target_pose # pose where the boxes should be placed

---

# Result
raw_vfk_dummy/Delivery[] deliveries # exact poses where each box is placed (depending on free space near target_pose)

---

# Feedback
int32 current_box_id
float32 percent_complete
